# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup JDK 11, so `sbt` can work properly
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Verify that all scala files are formatted properly
      - name: format-check
        run: sbt scalafmtCheck

      # Generate verilog code
      - name: generate-verilog
        run: make verilog

      # Build a behavioral model for Verilog code
      - name: build-simulator
        run: |
          sudo apt-get install -y verilator
          make sim

      # Run all regression tests and check the results
      - name: run-tests
        run: |
          sudo apt-get install -y qemu-user gcc-riscv64-unknown-elf
          make test

  # This workflow is just a empty workflow that tells `bors` whether CI succeeds
  ci-success:
    name: ci
    if: ${{ success() }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
